const events = [
  { date: "2026-03-09", source: "Republican Policy Retreat", quote: "It's going to be finished pretty quickly." },
  { date: "2026-03-23", source: "Press gaggle outside Air Force One", quote: "We have had very, very strong talks. We'll see where they lead. We have points, major points of agreement, I would say, almost all points of agreement" },
  { date: "2026-03-24", source: "Swearing In Ceremony of Markwayne Mullin", quote: "Well, I think we're going to end it. I can't tell you for sure. You know, I don't like to say this, we've won this -- this war has been won." },
  { date: "2026-03-25", source: "Public remarks", quote: "They want to make a deal so badly." },
  { date: "2026-03-26", source: "Cabinet meeting", quote: "They are begging to make a deal." },
  { date: "2026-03-29", source: "Air Force One gaggle", quote: "I do see a deal in Iran, yeah. It could be soon." },
  { date: "2026-03-31", source: "Remarks in Oval Office (for EO on elections)", quote: "I think two or three weeks. Yeah." },
  { date: "2026-04-01", source: "White House Address", quote: "We are going to finish the job and we're going to finish it very fast. We're getting very close." },
  { date: "2026-04-06", source: "White House Press Conference", quote: "We were very close to a deal." },
  { date: "2026-04-07", source: "Truth Social", quote: "A two week period will allow the Agreement to be finalized and consummated." },
  { date: "2026-04-15", source: "Fox Business", quote: "I think it's close to over. I view it as very close to over." },
  { date: "2026-04-16", source: "Event in Las Vegas", quote: "The war in Iran is going along swimmingly. We can do whatever we want and it should be ending pretty soon." },
  { date: "2026-04-16", source: "White House gaggle", quote: "It's looking very good that we're going to make a deal with Iran." },
  { date: "2026-04-17", source: "Axios phone interview", quote: "I think we will get a deal in the next day or two." },
  { date: "2026-04-20", source: "Truth Social", quote: "It will all happen, relatively quickly!" },
  { date: "2026-04-30", source: "Public remarks", quote: "They are dying to make a deal." },
  { date: "2026-05-01", source: "Press gaggle outside Air Force One", quote: "When the war ends, which shouldn't be too long..." },
  { date: "2026-05-06", source: "Remarks in Oval Office with UFC Fighters", quote: "We've had very good talks over the last 24 hours, and it's very possible that we'll make a deal." },
  { date: "2026-05-07", source: "Press gaggle at Reflecting Pool", quote: "It could happen any day. I believe they want the deal more than I do." },
  { date: "2026-05-18", source: "Public remarks", quote: "We thought pretty much getting close to making a deal and it didn't work out. But this is a little bit different." },
  { date: "2026-05-19", source: "Congressional picnic", quote: "We're gonna end that war very quickly." },
  { date: "2026-05-19", source: "Healthcare Affordability Event", quote: "[The gulf States] think that they are getting very close to making a deal." },
  { date: "2026-05-19", source: "Press gaggle", quote: "But I got a call yesterday, sir, can you wait? We think we're close to a deal." },
  { date: "2026-05-23", source: "Public remarks", quote: "The deal is largely negotiated, subject to finalization. We'll announce it shortly." },
  { date: "2026-05-23", source: "Truth Social", quote: "Final aspects and details of the Deal are currently being discussed, and will be announced shortly." },
  { date: "2026-05-28", source: "Interview with Lara Trump", quote: "We're close to a very good deal." },
  { date: "2026-06-05", source: "Kristen Welker Interview", quote: "And we're very close to having a deal. And if we don't have a deal, we'll do it one way or the other. Either way, we win." },
  { date: "2026-06-07", source: "Axios", quote: "We are very close to a final deal with Iran. It is going to be a good deal." },
  { date: "2026-06-08", source: "Truth Social", quote: "Final negotiations on “Peace” are proceeding." },
  { date: "2026-06-09", source: "Tele-rally for Sen. Graham", quote: "Total victory in the next two weeks. They're willing to give us everything." },
  { date: "2026-06-10", source: "Oval Office remarks", quote: "We’re really close to a deal." },
  { date: "2026-06-10", source: "Press gaggle outside Air Force One(after NBA Finals)", quote: "We're in the final throes of what will be a very, very good deal. Could be in two or three days." },
  { date: "2026-06-11", source: "Oval Office remarks", quote: "We just made a great settlement of the war with Iran, subject to finalization of documents. It should get done in the next few days." },
  { date: "2026-06-13", source: "Retruth of Pres. Sharif", quote: "We are closer to a peace deal than ever before. With finalisation likely expected in the next 24 hours." },
  { date: "2026-06-13", source: "Truth Social", quote: "The Deal is scheduled to get signed tomorrow." },
  { date: "2026-06-14", source: "Axios interview", quote: "[An Israeli strike in Lebanon] is so bad — I couldn't believe it. An hour before we are supposed to sign the deal." },
  { date: "2026-06-14", source: "Truth Social", quote: "We are very close to a Deal that will bring peace to the region, including to Lebanon..." },
  { date: "2026-06-14", source: "Truth Social", quote: "The Deal with the Islamic Republic of Iran is now complete. Congratulations to all!" },
  { date: "2026-06-14", source: "Truth Social", quote: "With the opening of the Strait upon the signing of the Deal on Friday..." },
  { date: "2026-06-15", source: "G7 Bilateral with Pres. Macron", quote: "I'm very happy to say [sic] very signed the deal is all signed and the strait is already partially opened." },
  { date: "2026-06-15", source: "G7 Bilateral with Pres. Macron", quote: "The Iran deal that we made is going to bring a lot of a lot of success to the world, because the oil was really clogged up there for a while." },
  { date: "2026-06-15", source: "G7 Bilateral with UAE", quote: "And we just signed a deal with Iran and this country was very, very -- a very powerful ally and good things are happening." },
  { date: "2026-06-15", source: "G7 Bilateral with Qatar", quote: "I'll not only release it, I'll probably have a press conference and read it to you word by word, so that the press covers it accurately." },
  { date: "2026-06-15", source: "G7 Bilateral with Qatar", quote: "We have our deal done with Iran and, uh, it should be successful." },
  { date: "2026-06-17", source: "G7 presser", quote: "You know, deals are amazing. I’ve done them all my life...I’ve gone into deals that were 100% — and they don’t happen...I think it’ll be done, they want to sign." },
  { date: "2026-06-17", source: "G7 press gaggle", quote: "[The memorandum is] signed, yeah. It's signed." },
  { date: "2026-06-23", source: "Truth Social", quote: "Iran has fully and completely agreed to highest level Nuclear inspections long into the future (Infinity!!!). This will insure “Nuclear Honesty.” If they did not agree to this, there would be no further negotiations!" },
  { date: "2026-06-23", source: "Truth Social", quote: "So, I have Iran on the “ropes,” ready to go down for the fall, willing to give us practically anything, and for the first time in decades, respecting the hell out of the United States and its President, ME..." },
  { date: "2026-06-25", source: "White House remarks", quote: "They wanna make a deal with us very badly, and, uh, we probably will." },
  { date: "2026-06-25", source: "Tele-rally for Julia Letlow", quote: "Iran, as you know, they want to make a deal and we're close to making a deal, but we're not going to let Iran have a nuclear weapon. It's very simple. And they've agreed to that." },
  { date: "2026-06-26", source: "Chippewa Falls rally", quote: "We're straightening out a little unfinished business in Iran" },
  { date: "2026-06-26", source: "Chippewa Falls rally", quote: "Obviously, this [Hormuz drone attack] is a foolish violation of our Ceasefire Agreement" },
  { date: "2026-06-27", source: "Truth Social", quote: "There may come a point when we are no longer able to be reasonable, and will be forced to militarily complete the job that we very successfully started. If that happens, the Islamic Republic of Iran will no longer exist!" },
  { date: "2026-06-29", source: "Truth Social", quote: "IRAN HAS REQUESTED A MEETING. IT WILL TAKE PLACE TOMORROW IN DOHA!" },
  { date: "2026-06-29", source: "Oval Office remarks", quote: "There'll be a meeting on that tomorrow, and Doha...so we'll see how that goes, but we're doing very well on that front." },
  { date: "2026-06-30", source: "Truth Social", quote: "Oil Prices are dropping sharply, even as we Denuclearize Iran. We are delivering on the promises that politicians talked about for decades, but never got done." },
  { date: "2026-07-01", source: "Air Force One press gaggle", quote: "As far as things are going, the denuclearization of Iran is moving along well." },
  { date: "2026-07-02", source: "Joe Kernen (CNBC) Oval Office interview", quote: "And we're negotiating...I think they've agreed to just about everything we need." },
  { date: "2026-07-03", source: "Mount Rushmore remarks", quote: "We beat Venezuela in one day and we knocked the hell out of Iran. They're dying to settle." },
  { date: "2026-07-06", source: "Rose Garden remarks", quote: "The relationship is very, very good, and we're doing very well with Iran...They want to make a deal so badly, but we'll see what happens." },
  { date: "2026-07-06", source: "Oval Office remarks", quote: "We're close to maybe making a deal...We're either going to make a deal or we're going to finish the job, OK?" },
  { date: "2026-07-08", source: "NATO remarks in Ankara", quote: "To me, I think [the ceasefire/MOU] is over. I don't want to deal with them anymore. They're scum. You know what scum is? They're scum. They're sick people" },
  { date: "2026-07-08", source: "Air Force One gaggle", quote: "I just don’t know if they’re worthy of making a deal. I don’t know that they’re going to honor the deal."},
  { date: "2026-07-08", source: "Truth Social", quote: "The Islamic Republic of Iran has asked us to continue “talks.” We have agreed to do so, but the United States has stated to them, in no uncertain terms, that the Cease Fire is OVER!"},
  { date: "2026-07-10", source: "Truth Social", quote: "The Islamic Republic of Iran has asked us to continue “talks.” We have agreed to do so, but the United States has stated to them, in no uncertain terms, that the Cease Fire is OVER!"},
  { date: "2026-07-11", source: "Truth Social", quote: "1000 Missiles are Locked and Loaded and aimed at the Islamic Republic of Iran..."},
  { date: "2026-07-13", source: "Hugh Hewitt interview", quote: "We had a deal yesterday. It was like going to be 100 percent. And then all of a sudden, they got a phone call and they all ran out of the room."},
  { date: "2026-07-13", source: "Hugh Hewitt interview", quote: "Memorandum of understanding when you're dealing with Sleazebags don't mean much."},
  { date: "2026-07-13", source: "Fox and Friends interview", quote: "We had a deal. It was a done deal and then they broke it. They always break it. We've had 10 deals with these people, and so we're just going to hit them very hard."},
  { date: "2026-07-13", source: "Fox and Friends interview", quote: "We're putting the blockade back and it's a blockade...The blockade was probably more effective even than hitting them."},
  { date: "2026-07-13", source: "Oval Office remarks", quote: "We had a deal yesterday or the day before yesterday, it was all done and then they broke up that deal immediately because they found out there was something in the deal they didn't like."},
  { date: "2026-07-14", source: "Oval Office remarks with al-Zaidi", quote: "I wanted to give them a chance at making a deal. We had a deal two days ago, it was done. And then all of a sudden, they couldn't do it - they didn't like something about the deal, they couldn't do it. "},
  { date: "2026-07-14", source: "Trey Yingst interview", quote: "I think they have no choice [to make a deal]...Well, now we, I don't wanna negotiate now. I said, 'Let's not negotiate.' Three days ago, we had a deal."},
  { date: "2026-07-14", source: "Truth Social", quote: "the Strait of Hormuz is open to ALL Ship traffic except for Iran"},
  { date: "2026-07-15", source: "Army War College remarks", quote: "The country is booming, and we'll have Iran defeated soon, they'll be defeated very soon."},
  { date: "2026-07-15", source: "Fox Business interview", quote: "They're nasty people, but they want to make a deal. I can tell you they want to make a deal. "},
  { date: "2026-07-16", source: "Primetime Address", quote: "We are likewise winning big in Iran, and you will see the fruits of that labor very, very shortly."},
  { date: "2026-07-21", source: "Bilateral with Aoun of Lebanon", quote: "And our deal will be a wall, it already is."},
  { date: "2026-07-22", source: "Trump speech in Marietta, Georgia", quote: "But I say, they're not ready to make a deal because every time they make a deal, they want to change it and everything. They're not ready. They'll be ready very soon."},
  { date: "2026-07-22", source: "Truth Social", quote: "From this point forward, any time the Islamic Republic of Iran shoots at a ship in the Strait of Hormuz...the United States will bomb and destroy ONE BRIDGE OR POWER PLANT..."},
  { date: "2026-07-23", source: "Trump comments at EPA", quote: "We're doing very well against the Islamic Republic of Iran. We're doing extremely well. They would like to do something, but I say they're not ready yet."},
  { date: "2026-07-24", source: "White House comments", quote: "There's a military exit where we just keep going just the way we are, and we can even make it a heavier dose...Or there's a smarter strategy that you make a deal. And they want to make a deal. I just don't think they're ready yet."},
  { date: "2026-07-24", source: "White House Correspondents Association Dinner", quote: "They'd love to make a deal. I don't think they're ready to. I don't think it's time yet, but I'm willing to listen."},
  { date: "2026-07-27", source: "Air Force One gaggle", quote: "They want to meet and we're meeting. We'll see what happens. There's a chance we could make a deal. Without what we did, they wouldn't even be talking to us."},
  { date: "2026-07-27", source: "Speech at GM", quote: "And right now they're talking to us about making a deal. But if we didn't do it tough, there would be no talk."},
  { date: "2026-07-28", source: "FOX News phone interview", quote: "I know exactly what's going on at Pickax, it's not a big problem. We took out their nuclear sites, and we'll have to take out Pickax if we don't make a deal. If we don't make a deal, we'll take it out very easily."},
  { date: "2026-07-28", source: "FOX News phone interview", quote: "So, we [lifted the Hormuz blockade], and then we put it back because they broke the deal. They broke the deal. We cannot have them break deals anymore."},
  { date: "2026-07-28", source: "Tele-rally for Andy Ogles", quote: "We've taken them, we've hit them very hard and they wanna make a deal so badly."},
  { date: "2026-07-29", source: "Tele-rally for Michael Alfonso", quote: "We'll finish off Iran pretty soon. It's gonna happen."},
  { date: "2026-07-31", source: "Camp David cabinet meeting", quote: "Just in case you read incorrect stories, they're doing very, very poorly. They're having a hard time. They've been very dishonest. They've been very dishonorable to deal with, but that makes no difference."},
  { date: "2026-07-31", source: "Camp David cabinet meeting", quote: "We have the best people, but they'll make a deal."},
  { date: "2026-08-01", source: "Truth Social", quote: "We have just been asked by Iran, and other Middle Eastern Countries, to hold off any attack in that the perimeters of a deal has been agreed to."},
  { date: "2026-08-02", source: "Truth Social", quote: "I have agreed, for the future benefit of the WORLD and, likewise, the survival of a successful and prosperous Iran, to cancel the [biggest attack since WWII], subject to being able to rapidly make a DEAL."},
  { date: "2026-08-02", source: "Air Force One gaggle", quote: "There's a deal on Hormuz and then there will be a deal on the nuclear, or you might call it the denuclearization of Iran."},
  { date: "2026-08-02", source: "Air Force One gaggle", quote: "Uh, we were also asked by Iran very strongly, actually. Uh, they said, \"We'd like to make a deal.\""},
  { date: "2026-08-03", source: "Truth Social", quote: "Whether Iran wants to admit it or not, we are, in fact, talking of a solution to a problem that they have caused, for decades."},
  { date: "2026-08-03", source: "Oval Office presser", quote: "So I say, we're in talks, big deal, we're in talks."},
  { date: "2026-08-03", source: "Oval Office presser", quote: "This is a last chance. This is not something that if it doesn't happen -- this is a last chance for them to sign a good document."},
  { date: "2026-08-04", source: "Fox News Trace Gallagher interview", quote: "And they want to make a deal. We'll see what happens. If they don't make a deal, it's going to be too bad."},
  { date: "2026-08-04", source: "Press gaggle outside Air Force One", quote: "And I think it'd be very smart to make a deal. We'll see what happens. Uh, they had a very good day. The negotiations were good. The stock market was up tremendously over the last three, four days."},
  { date: "2026-08-04", source: "Press gaggle outside Air Force One", quote: "[The Strait of Hormuz opening tomorrow:] It could happen. Tomorrow or the next day, yeah."},
  { date: "2026-08-05", source: "Las Vegas rally", quote: "We're knocking the hell out of them. I'd rather make a deal because I don't want to kill people...But we are talking, let's see what happens. But they respect us, they respect us."},
  { date: "2026-08-06", source: "Oval Office comments", quote: "But I think we’re doing very well. I just, you know, I’m involved in the negotiation. I think it’s doing fine. It could be soon."},
  { date: "2026-08-07", source: "Truth Social shared article", quote: "Donald Trump Won The Iran War"},
  { date: "2026-08-09", source: "Axios interview", quote: "We are low keying it...We are only semi-negotiating with them...It will work out. It always works out."},
 
];